export {default as MediaPartners} from './MediaPartners';
export {default as Intro} from './Intro';
export {default as Performance} from './Performance';
export {default as ServiceProvider} from './ServiceProvider';
export {default as Services} from './Services';
export {default as Feedback} from './Feedback';
export {default as Quiz} from './Quiz';
export {default as Psychologist} from './Psychologist';
export {default as HowItWorks} from './HowItWorks';